[profile.default]
src = "contracts"
test = "contracts"
libs = ["target/forge_dependencies"]
out = "target/contracts/out"
cache_path = "target/contracts/cache"
remappings = [
    "@openzeppelin/contracts-upgradeable/=target/forge_dependencies/@openzeppelin-contracts-upgradeable-5.1.0/",
    "@openzeppelin/contracts/=target/forge_dependencies/@openzeppelin-contracts-5.1.0/",
    "forge-std/=target/forge_dependencies/forge-std-1.9.4/src/"
]

[dependencies]
"forge-std" = "1.9.4"
"@openzeppelin-contracts-upgradeable" = "5.1.0"
"@openzeppelin-contracts" = "5.1.0"
